name: Commit code to main server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  buildAndCommit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Cache dependencies
        uses: actions/cache@v3.3.2
        with:
          path: |
            node_modules
            yarn.lock
            package-lock.json
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-

      - name: Resolve dependencies
        run: yarn

      - name: Build
        run: npm run compile

      - name: Commit code to main server
        run: |
          grunt
        env:
          SCREEPS_EMAIL: ${{ secrets.SCREEPS_EMAIL }}
          SCREEPS_AUTH_TOKEN: ${{ secrets.SCREEPS_AUTH_TOKEN }}

  codeAnalysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Cache dependencies
        uses: actions/cache@v3.3.2
        with:
          path: |
            node_modules
            yarn.lock
            package-lock.json
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-

      - name: Resolve dependencies
        run: yarn

      - name: Code Analysis
        run: npm run lint
